### ISSUE TITLE
Bug maluco quando o sistema está desconectado do BD

### ISSUE THREAD

**Issue by lennedy** [expotec-sc-desenvolvimento/sistemadesubmissao#10]

**Comment by lennedy** [comment]
aparentemente o sistema quando não está conectado ao banco de dados entra nas páginas subsequentes do site sem ter acesso completo ao banco.

**Comment by sueneylima** [comment]
Em todas as páginas (exceto as de recuperação de senha e cadastro), é verificado se o usuário está logado... caso contrário, ele é encaminhado para a página de Login. Parece que esse erro só ocorre quando o usuário, já logado, perde a conexão com o BD. Tem duas opções: 1. Finalizar a sessão quando houver um problema de conexão com o BD... ou 2. Impedir que informações posteriores apareçam na tela quando houver a ocorrência de algum erro na conexão!
