### ISSUE TITLE
Implementação do envio automatizado dos e-mails 

### ISSUE THREAD

**Issue by lennedy** [expotec-sc-desenvolvimento/sistemadesubmissao#8]

**Comment by sueneylima** [comment]
Funcionando parcialmente para inserção de Avaliações.

**Comment by sueneylima** [comment]
Realizei testes com o envio de email. Problemas foram encontrados devido a todos os usuários estarem com o mesmo email. A classe PHPMail está travando com o envio de vários emails para o mesmo email. O teste de atribuição de várias submissões ao mesmo tempo ficou prejudicado por não haver emails suficientes para testes.

Quando o teste foi realizado individualmente, com emails diferentes dos avaliadores, foi obtido 100% de sucesso! Recomenda-se, dessa forma, que seja utilizada a atribuição automática quando é feita a submissão, ou a atribuição individual por submissão, o que trará menos carga para a aplicação!
